from io import BytesIO
from pathlib import Path

from fastapi.testclient import TestClient
from PIL import Image

from palette_card.config import Paths
from palette_card.runtime import ProductionSettings
from palette_card.server import create_production_app


def test_health_and_fail_closed_readiness(tmp_path: Path):
    settings = ProductionSettings(
        host="127.0.0.1",
        port=7860,
        output_dir=tmp_path / "cards",
        checkpoint=tmp_path / "missing-object.pt",
        palette_checkpoint=tmp_path / "missing-palette.pt",
        max_upload_mb=2,
        max_pixels=1_000_000,
        concurrency=1,
        queue_size=2,
        retention_hours=24,
        require_models=True,
        allowed_hosts=("testserver",),
        username=None,
        password=None,
        log_level="warning",
    )
    with TestClient(create_production_app(settings)) as client:
        root = client.get("/")
        styles = client.get("/frontend/styles.css?v=4")
        health = client.get("/healthz")
        ready = client.get("/readyz")
        generate = client.post(
            "/api/generate",
            files={"file": ("sample.png", b"not-needed", "image/png")},
        )
    assert root.status_code == 200
    assert "PaletteCard AI" in root.text
    assert 'data-view="how"' in root.text
    assert 'data-view="editor"' in root.text
    assert 'data-view="privacy"' in root.text
    assert 'id="artboard"' in root.text
    assert styles.status_code == 200
    assert 'font-family: "Schoolbell"' in styles.text
    assert health.status_code == 200
    assert health.headers["x-content-type-options"] == "nosniff"
    assert ready.status_code == 503
    assert ready.json()["status"] == "not_ready"
    assert generate.status_code == 503


def test_ai_api_returns_inline_cards_without_ephemeral_file_urls(tmp_path: Path, monkeypatch):
    monkeypatch.setenv("PALETTECARD_MOUNT_GRADIO", "false")
    paths = Paths()
    settings = ProductionSettings(
        host="127.0.0.1",
        port=7860,
        output_dir=tmp_path / "cards",
        checkpoint=paths.default_checkpoint,
        palette_checkpoint=paths.palette_checkpoint,
        max_upload_mb=2,
        max_pixels=1_000_000,
        concurrency=1,
        queue_size=2,
        retention_hours=24,
        require_models=True,
        allowed_hosts=("testserver",),
        username=None,
        password=None,
        log_level="warning",
    )
    image = Image.new("RGB", (96, 96), (220, 80, 125))
    source = BytesIO()
    image.save(source, "PNG")
    with TestClient(create_production_app(settings)) as client:
        response = client.post(
            "/api/generate",
            data={
                "object_choice": "flower",
                "title": "A test card",
                "message": "Generated by both models.",
            },
            files={"file": ("flower.png", source.getvalue(), "image/png")},
        )
    assert response.status_code == 200
    assert len(response.content) < 4_500_000
    payload = response.json()
    assert payload["status"] == "ready"
    assert payload["model_mode"] is True
    assert len(payload["source_colors"]) == 5
    assert len(payload["cards"]) == 3
    assert all(card["data_url"].startswith("data:image/jpeg;base64,") for card in payload["cards"])
    assert not list((tmp_path / "cards").glob("palette-card-*.png"))
